[component]
structures = [ "content_blocks" ]
label = "Project Preview"
description = "Section to add a project preview"
icon = "wysiwyg"
tags = ["Structure", "Text", "Links"]

[props]
title = "Project Title"
description_html = "Short Description of your project"
image = "/images/01.jpg"
image_alt = "Vanessa Marley's picture"
link_url = "/projects"
